//  pqueue_ip.h : précisions sur l'implantation du module pqueue.

//  pqueue_empty : temps ... ; espace ....
//  pqueue_dispose : temps ... ; espace ....
//  pqueue_enqueue : temps ... ; espace ....
//  pqueue_dequeue : temps ... ; espace ....
//  pqueue_head : temps ... ; espace ....
//  pqueue_is_empty : temps ... ; espace ....
//  pqueue_length : temps ... ; espace ....
